[package]
name = "email-fanout"
version = "0.1.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
addr = "0.15.6"
clap = { version = "4.0.29", features = ["derive","env"] }
imap = "2.4.1"
lettre = "0.10.1"
mailparse = "0.13.8"
native-tls = "0.2.11"
