[package]
name = "email-forwarder"
version = "0.1.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
addr = "0.15.6"
clap = { version = "4.1.11", features = ["derive","env"] }
imap = "2.4.1"
lettre = "0.10.3"
log = "0.4.17"
native-tls = "0.2.11"
simple_logger = "4.0.0"
