[package]
name = "email-forwarder"
version = "0.1.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
addr = "0.15.6"
anyhow = "1.0.82"
clap = { version = "4.5.4", features = ["derive","env"] }
ctrlc = { version = "3.4.4", features = ["termination"] }
imap = "2.4.1"
lettre = "0.11.7"
log = "0.4.21"
native-tls = "0.2.11"
openssl = { version = "0.10.64", features = ["vendored"] }
simple_logger = "4.3.3"
